package com.ral.model.entity.member;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class MemberType implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_type.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_type.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_type.icon
     *
     * @mbggenerated
     */
    private Long icon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_type.min
     *
     * @mbggenerated
     */
    private BigDecimal min;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_type.max
     *
     * @mbggenerated
     */
    private BigDecimal max;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_type.is_discount
     *
     * @mbggenerated
     */
    private Boolean isDiscount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_type.discount
     *
     * @mbggenerated
     */
    private BigDecimal discount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_type.desc
     *
     * @mbggenerated
     */
    private String desc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_type.create_user
     *
     * @mbggenerated
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_type.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_type.last_update_user
     *
     * @mbggenerated
     */
    private String lastUpdateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_type.last_update_time
     *
     * @mbggenerated
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_type.is_disable
     *
     * @mbggenerated
     */
    private Boolean isDisable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table member_type
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_type.id
     *
     * @return the value of member_type.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_type.id
     *
     * @param id the value for member_type.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_type.name
     *
     * @return the value of member_type.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_type.name
     *
     * @param name the value for member_type.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_type.icon
     *
     * @return the value of member_type.icon
     *
     * @mbggenerated
     */
    public Long getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_type.icon
     *
     * @param icon the value for member_type.icon
     *
     * @mbggenerated
     */
    public void setIcon(Long icon) {
        this.icon = icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_type.min
     *
     * @return the value of member_type.min
     *
     * @mbggenerated
     */
    public BigDecimal getMin() {
        return min;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_type.min
     *
     * @param min the value for member_type.min
     *
     * @mbggenerated
     */
    public void setMin(BigDecimal min) {
        this.min = min;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_type.max
     *
     * @return the value of member_type.max
     *
     * @mbggenerated
     */
    public BigDecimal getMax() {
        return max;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_type.max
     *
     * @param max the value for member_type.max
     *
     * @mbggenerated
     */
    public void setMax(BigDecimal max) {
        this.max = max;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_type.is_discount
     *
     * @return the value of member_type.is_discount
     *
     * @mbggenerated
     */
    public Boolean getIsDiscount() {
        return isDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_type.is_discount
     *
     * @param isDiscount the value for member_type.is_discount
     *
     * @mbggenerated
     */
    public void setIsDiscount(Boolean isDiscount) {
        this.isDiscount = isDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_type.discount
     *
     * @return the value of member_type.discount
     *
     * @mbggenerated
     */
    public BigDecimal getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_type.discount
     *
     * @param discount the value for member_type.discount
     *
     * @mbggenerated
     */
    public void setDiscount(BigDecimal discount) {
        this.discount = discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_type.desc
     *
     * @return the value of member_type.desc
     *
     * @mbggenerated
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_type.desc
     *
     * @param desc the value for member_type.desc
     *
     * @mbggenerated
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_type.create_user
     *
     * @return the value of member_type.create_user
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_type.create_user
     *
     * @param createUser the value for member_type.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_type.create_time
     *
     * @return the value of member_type.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_type.create_time
     *
     * @param createTime the value for member_type.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_type.last_update_user
     *
     * @return the value of member_type.last_update_user
     *
     * @mbggenerated
     */
    public String getLastUpdateUser() {
        return lastUpdateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_type.last_update_user
     *
     * @param lastUpdateUser the value for member_type.last_update_user
     *
     * @mbggenerated
     */
    public void setLastUpdateUser(String lastUpdateUser) {
        this.lastUpdateUser = lastUpdateUser == null ? null : lastUpdateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_type.last_update_time
     *
     * @return the value of member_type.last_update_time
     *
     * @mbggenerated
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_type.last_update_time
     *
     * @param lastUpdateTime the value for member_type.last_update_time
     *
     * @mbggenerated
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_type.is_disable
     *
     * @return the value of member_type.is_disable
     *
     * @mbggenerated
     */
    public Boolean getIsDisable() {
        return isDisable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_type.is_disable
     *
     * @param isDisable the value for member_type.is_disable
     *
     * @mbggenerated
     */
    public void setIsDisable(Boolean isDisable) {
        this.isDisable = isDisable;
    }
}