package com.ral.dao.item;

import com.ral.model.entity.item.ItemSpec;
import com.ral.model.entity.item.ItemSpecExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface ItemSpecMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_spec
     *
     * @mbggenerated
     */
    int countByExample(ItemSpecExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_spec
     *
     * @mbggenerated
     */
    int deleteByExample(ItemSpecExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_spec
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_spec
     *
     * @mbggenerated
     */
    int insert(ItemSpec record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_spec
     *
     * @mbggenerated
     */
    int insertSelective(ItemSpec record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_spec
     *
     * @mbggenerated
     */
    List<ItemSpec> selectByExample(ItemSpecExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_spec
     *
     * @mbggenerated
     */
    ItemSpec selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_spec
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ItemSpec record, @Param("example") ItemSpecExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_spec
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ItemSpec record, @Param("example") ItemSpecExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_spec
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ItemSpec record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_spec
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ItemSpec record);


    int selectActiveByItemCodeAndSpecId(@Param("itemCode")String itemCode,@Param("specId") Long specId);
}