package com.ral.auth.dao;

import com.ral.auth.model.entity.Action;
import com.ral.auth.model.entity.ActionExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface ActionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_action
     *
     * @mbggenerated
     */
    int countByExample(ActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_action
     *
     * @mbggenerated
     */
    int deleteByExample(ActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_action
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_action
     *
     * @mbggenerated
     */
    int insert(Action record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_action
     *
     * @mbggenerated
     */
    int insertSelective(Action record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_action
     *
     * @mbggenerated
     */
    List<Action> selectByExample(ActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_action
     *
     * @mbggenerated
     */
    Action selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_action
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Action record, @Param("example") ActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_action
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Action record, @Param("example") ActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_action
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Action record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_action
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Action record);

    List<Action> selectByRoleIdAndMoudleId(@Param("roleId") String roleId, @Param("moduleId") String moduleId);
}