package com.ral.auth.dao;

import com.ral.auth.model.entity.RoleModule;
import com.ral.auth.model.entity.RoleModuleExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface RoleModuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role_module
     *
     * @mbggenerated
     */
    int countByExample(RoleModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role_module
     *
     * @mbggenerated
     */
    int deleteByExample(RoleModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role_module
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role_module
     *
     * @mbggenerated
     */
    int insert(RoleModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role_module
     *
     * @mbggenerated
     */
    int insertSelective(RoleModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role_module
     *
     * @mbggenerated
     */
    List<RoleModule> selectByExample(RoleModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role_module
     *
     * @mbggenerated
     */
    RoleModule selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role_module
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") RoleModule record, @Param("example") RoleModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role_module
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") RoleModule record, @Param("example") RoleModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role_module
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RoleModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role_module
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RoleModule record);
}