package com.ral.auth.dao;

import com.ral.auth.model.entity.RoleAction;
import com.ral.auth.model.entity.RoleActionExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface RoleActionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role_action
     *
     * @mbggenerated
     */
    int countByExample(RoleActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role_action
     *
     * @mbggenerated
     */
    int deleteByExample(RoleActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role_action
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role_action
     *
     * @mbggenerated
     */
    int insert(RoleAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role_action
     *
     * @mbggenerated
     */
    int insertSelective(RoleAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role_action
     *
     * @mbggenerated
     */
    List<RoleAction> selectByExample(RoleActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role_action
     *
     * @mbggenerated
     */
    RoleAction selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role_action
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") RoleAction record, @Param("example") RoleActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role_action
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") RoleAction record, @Param("example") RoleActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role_action
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RoleAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role_action
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RoleAction record);
}