package com.ral.auth.dao;

import com.ral.auth.model.entity.Tenant;
import com.ral.auth.model.entity.TenantExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface TenantMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tenant
     *
     * @mbggenerated
     */
    int countByExample(TenantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tenant
     *
     * @mbggenerated
     */
    int deleteByExample(TenantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tenant
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tenant
     *
     * @mbggenerated
     */
    int insert(Tenant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tenant
     *
     * @mbggenerated
     */
    int insertSelective(Tenant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tenant
     *
     * @mbggenerated
     */
    List<Tenant> selectByExample(TenantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tenant
     *
     * @mbggenerated
     */
    Tenant selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tenant
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Tenant record, @Param("example") TenantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tenant
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Tenant record, @Param("example") TenantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tenant
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Tenant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tenant
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Tenant record);
}